"""Report/visualization service for the web app.

Wraps the existing ``viz`` package (OrangePlot, BalanceChart, CustodyChart,
PDFReport) so charts and the combined PDF can be generated on demand and
streamed as bytes from FastAPI routes.

Design notes:
- Forces the non-interactive ``Agg`` matplotlib backend *before* the viz
  modules (which import ``matplotlib.pyplot`` at import time) are imported.
  Without this a headless server can hang or crash trying to open a GUI
  backend.
- matplotlib's pyplot state machine is not thread-safe. Uvicorn runs sync
  route handlers in a threadpool, so all figure generation is serialized
  behind a module-level lock. This is fine for a single-operator app.
- Generated bytes are cached in-process with a short TTL to avoid
  regenerating three matplotlib figures (plus a yfinance call) on every
  ``<img>`` request and again for the PDF. Pass ``refresh=True`` to bypass.
"""

from __future__ import annotations

import os
import tempfile
import threading
import time
from pathlib import Path
from typing import TYPE_CHECKING

# Force a headless backend before anything imports pyplot.
os.environ.setdefault("MPLBACKEND", "Agg")
import matplotlib

matplotlib.use("Agg", force=True)

from viz import BalanceChart, CustodyChart, OrangePlot, PDFReport, VizConfig

if TYPE_CHECKING:
    from db import DatabaseBackend

# Chart type -> generator class. Keys are the public API values.
_CHART_CLASSES = {
    "orange": OrangePlot,
    "balance": BalanceChart,
    "custody": CustodyChart,
}

VALID_CHARTS = tuple(_CHART_CLASSES.keys())
VALID_RANGES = ("all", "5y", "1y", "ytd")

# Rendering resolution for the web. 150 DPI on a 10x6 figure -> ~1500x900,
# crisp on retina while keeping payloads small.
_WEB_DPI = 150

# matplotlib pyplot is a global state machine; serialize all generation.
_render_lock = threading.Lock()

# Simple in-process byte cache: key -> (expires_at, content_bytes).
_CACHE_TTL_SECONDS = int(os.getenv("REPORTS_CACHE_TTL_SECONDS", "300"))
_cache: dict[str, tuple[float, bytes]] = {}
_cache_lock = threading.Lock()


class ReportError(RuntimeError):
    """Raised when a chart or report cannot be generated (e.g. no data)."""


def _cache_get(key: str) -> bytes | None:
    with _cache_lock:
        entry = _cache.get(key)
        if entry is None:
            return None
        expires_at, content = entry
        if time.monotonic() >= expires_at:
            _cache.pop(key, None)
            return None
        return content


def _cache_put(key: str, content: bytes) -> None:
    if _CACHE_TTL_SECONDS <= 0:
        return
    with _cache_lock:
        _cache[key] = (time.monotonic() + _CACHE_TTL_SECONDS, content)


def clear_cache() -> None:
    """Drop all cached report bytes (e.g. after a ledger mutation)."""
    with _cache_lock:
        _cache.clear()


def _config(output_dir: Path, date_range: str) -> VizConfig:
    return VizConfig(
        date_range=date_range,
        output_dir=output_dir,
        include_cost_basis=True,
        log_scale=False,
        dpi=_WEB_DPI,
    )


def render_chart_png(
    backend: DatabaseBackend,
    chart_type: str,
    *,
    date_range: str = "all",
    refresh: bool = False,
) -> bytes:
    """Render a single chart to PNG bytes.

    Args:
        backend: Request-scoped database backend.
        chart_type: One of ``VALID_CHARTS``.
        date_range: One of ``VALID_RANGES``.
        refresh: Bypass the byte cache and regenerate.

    Raises:
        ValueError: Invalid ``chart_type`` or ``date_range``.
        ReportError: No transaction data / generation failed.
    """
    if chart_type not in _CHART_CLASSES:
        raise ValueError(f"Unknown chart type: {chart_type!r}")
    if date_range not in VALID_RANGES:
        raise ValueError(f"Unknown date range: {date_range!r}")

    cache_key = f"png:{chart_type}:{date_range}"
    if not refresh:
        cached = _cache_get(cache_key)
        if cached is not None:
            return cached

    chart_cls = _CHART_CLASSES[chart_type]
    with _render_lock:
        with tempfile.TemporaryDirectory(prefix="btc-viz-") as tmp:
            config = _config(Path(tmp), date_range)
            try:
                output_path = chart_cls(backend, config).generate()
            except (ValueError, RuntimeError) as exc:
                raise ReportError(str(exc)) from exc
            content = Path(output_path).read_bytes()

    _cache_put(cache_key, content)
    return content


def render_report_pdf(
    backend: DatabaseBackend,
    *,
    date_range: str = "all",
    refresh: bool = False,
) -> bytes:
    """Render the combined multi-page PDF report to bytes.

    Raises:
        ValueError: Invalid ``date_range``.
        ReportError: No transaction data / generation failed.
    """
    if date_range not in VALID_RANGES:
        raise ValueError(f"Unknown date range: {date_range!r}")

    cache_key = f"pdf:{date_range}"
    if not refresh:
        cached = _cache_get(cache_key)
        if cached is not None:
            return cached

    with _render_lock:
        with tempfile.TemporaryDirectory(prefix="btc-report-") as tmp:
            config = _config(Path(tmp), date_range)
            try:
                output_path = PDFReport(backend, config).generate()
            except (ValueError, RuntimeError) as exc:
                raise ReportError(str(exc)) from exc
            content = Path(output_path).read_bytes()

    _cache_put(cache_key, content)
    return content
