#!/usr/bin/python3
import sys
from cryptoAccounts import CryptoAccounts
crypto = CryptoAccounts()
if len(sys.argv) > 1:
	coin = sys.argv[1]
else:
	coin = "BTC"

print("*********************************************************************")
print("Accounts")
print("---------------------------------------------------------------------")
print("Vault\t" + f"{(crypto.get_balance_by_account(coin, 'Vault')):.8f}")
print("CC\t" + f"{(crypto.get_balance_by_account(coin, 'CC')):.8f}")
print("Strike\t" + f"{(crypto.get_balance_by_account(coin, 'Strike')):.8f}")
print("River\t" + f"{(crypto.get_balance_by_account(coin, 'River')):.8f}")
print("Kraken\t" + f"{(crypto.get_balance_by_account(coin, 'Kraken')):.8f}")
print("Ledger\t" + f"{(crypto.get_balance_by_account(coin, 'Ledger-2')):.8f}")
print("---------------------------------------------------------------------")
print("Total\t" + f"{(crypto.get_balance(coin)):.8f}")
print("Basis\t" + f"{(crypto.get_basis(coin)):.2f}")
print("*********************************************************************")
print()
